name: "Publish Release"

on:
  push:
    branches:
      - main # 监听 main 分支的变动

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须设为 0，否则无法获取历史版本进行自增

      # --- 关键步骤：自动生成 Tag ---
      - name: Auto Tag Generation
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # 默认每次推送到 main 都增加修订号 (x.x.1)

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

     # 1. 提取 package.json 中的版本号
      - name: Get version
        id: package_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # 2. 使用统一的版本号进行发布
      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 强制两个平台都指向同一个 Tag，例如 v1.0.2
          tagName: v${{ steps.package_version.outputs.version }}
          releaseName: "GIF Comp v${{ steps.package_version.outputs.version }}"
          releaseDraft: false
          prerelease: false